modLoader="javafml"
loaderVersion="[39,)"
license="All Rights go to Dreamworks"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="httymd"
version="1.0"
displayName="How to Train your Minecraft Dragon"
#updateJSONURL=""
displayURL=""
logoFile="logo.png"
credits=""
authors="Mnesikos, ZephyraNF, Ersh Gem" #optional
description='''A Minecraft mod that brings the world of How to Train your Dragon into the game!'''

[[dependencies.httymd2]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"

[[dependencies.httymd2]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"
